save_data: {*PATH}/example/

# Prevent overwriting existing files in the folder
overwrite: True

# Corpus opts:
data:
    train:
        path_src: {*PATH}/data/src_train.txt
        path_tgt: {*PATH}/data/tgt_train.txt
        src_seq_length: 100
        tgt_seq_length: 100
    valid:
        path_src: {*PATH}/data/src_validation.txt
        path_tgt: {*PATH}/data/tgt_validation.txt
        src_seq_length: 100
        tgt_seq_length: 100

# Where the vocab(s) will be written
src_vocab: {*PATH}/example.vocab.src
tgt_vocab: {*PATH}/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [ 0 ]

# supported types: GloVe, word2vec
word_vec_size: 100

# Where to save the checkpoints
save_model: {*PATH}/checkpoints/
save_checkpoint_steps: 10000
train_steps: 200000
valid_steps: 10000

encoder_type: brnn
decoder_type: rnn
rnn_type: LSTM
enc_layers: 2
dec_layers: 2
rnn_size: 512
learning_rate: 0.001
early_stopping: 4
optim: adam
learning_rate_decay: 0.01

tensorboard: True
tensorboard_log_dir: {*PATH}/board
